export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const USER_DATA_FETCH_SUCCESS = 'USER_DATA_FETCH_SUCCESS';
export const UPDATE_DELETE_SUCCESS = 'UPDATE_DELETE_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SUCCESS = 'SET_SUCCESS';
export const SET_ERRORS = 'SET_ERRORS';
